# Generated by Django 4.1.7 on 2023-03-25 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_note_is_content_html_alter_note_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='cover',
        ),
        migrations.AddField(
            model_name='note',
            name='card_cover',
            field=models.ImageField(blank=True, default='', upload_to='notes/card_covers/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='note',
            name='page_cover',
            field=models.ImageField(blank=True, default='', upload_to='notes/page_covers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
